version: '3.8'


services:
  postgres:
    container_name: postgres
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    depends_on:
    - csharpapp

  csharpapp:
    container_name: pzapi
    image: pzapi:dev
    build:
        context: .
    ports:
      - "8080:80"
    environment:
      ConnectionStrings__DefaultConnection: "Host=192.168.65.1;Database=postgres;Username=postgres;Password=postgres;Port=5432"



volumes:
  pgdata: {}
